source ./3-alter-table-primary-keys/sede.sql
source ./3-alter-table-primary-keys/ubicacion.sql
source ./3-alter-table-primary-keys/departamento.sql
source ./3-alter-table-primary-keys/grupo.sql
source ./3-alter-table-primary-keys/profesor.sql
source ./3-alter-table-primary-keys/paticipa.sql
source ./3-alter-table-primary-keys/proxecto.sql
source ./3-alter-table-primary-keys/programa.sql
source ./3-alter-table-primary-keys/financia.sql